services:

  gemini-dialogue:
    container_name: gemini-dialogue
    networks:
      - dialogueNetwork
    image: node:20-buster-slim
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    working_dir: /app
    env_file:
      - .env
    command: sh -c "npm install --verbose && npm start"

networks:
  dialogueNetwork:
    driver: bridge